#######################################
# Application
#######################################
spring.application.name=learn-spring-boot

#######################################
# Server
#######################################
server.port=9090

#######################################
# Logging
#######################################
logging.level.root=INFO

#######################################
# JPA
#######################################
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#######################################
# H2 Database (optional)
#######################################
spring.h2.console.enabled=true

#######################################
# Custom Properties
#######################################
app.version=1.0